(setq highlight-indent-guides-method 'column)
(setq highlight-indent-guides-auto-odd-face-perc 15)
(setq highlight-indent-guides-auto-even-face-perc 15)
(setq highlight-indent-guides-auto-character-face-perc 20)
(setq highlight-indent-guides-character ?\|)
(setq highlight-indent-guides-responsive 'top)
